// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterAPI.Models;

#nullable disable

namespace ShelterAPI.Migrations
{
    [DbContext(typeof(ShelterAPIContext))]
    [Migration("20230401011435_Validations")]
    partial class Validations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Gender = "male",
                            Name = "Scruff",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            Gender = "female",
                            Name = "Henri",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Gender = "male",
                            Name = "Brownie",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 9,
                            Gender = "female",
                            Name = "Petunia",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 1,
                            Gender = "unknown",
                            Name = "Dart",
                            Species = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
